from python:3.8

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

WORKDIR /second_component
COPY ./requirements.txt /second_component/requirements.txt
RUN pip install -r /second_component/requirements.txt
COPY . /second_component

EXPOSE 8000
CMD ["/bin/bash"]